# Generated by Django 2.2.17 on 2020-12-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='abcd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='efghi',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
